all: 01_utils 02_disk 03_mbr 04_distro 05_hypervisor 06_vm 07_inifile

01_utils:
	(cd $@ && make)
02_disk:
	(cd $@ && make)
03_mbr:
	(cd $@ && make)
04_distro:
	(cd $@ && make)
05_hypervisor:
	(cd $@ && make)
06_vm:
	(cd $@ && make)
07_inifile:
	(cd $@ && make)

.PHONY: 01_utils 02_disk 03_mbr 04_distro 05_hypervisor 06_vm 07_inifile
